name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1 # v6.0.1

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: '1.23'

      - name: Build provider
        working-directory: .
        run: |
          go build -o terraform-provider-infradots

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.10.7"

      - name: Setup provider
        working-directory: .github/tofu-tests
        run: |
          mkdir -p ~/.terraform.d/plugins/registry.terraform.io/local/infra-dots/infradots/1.3.0/linux_amd64/
          cp ../../terraform-provider-infradots ~/.terraform.d/plugins/registry.terraform.io/local/infra-dots/infradots/1.3.0/linux_amd64/

      - name: Initialize OpenTofu
        working-directory: .github/tofu-tests
        env:
          TF_LOG: INFO
        run: |
          tofu init

      - name: Run OpenTofu Apply
        working-directory: .github/tofu-tests
        env:
          TF_VAR_organization_name: ${{ secrets.INFRADOTS_ORGANIZATION_NAME }}
          TF_VAR_infradots_token: ${{ secrets.INFRADOTS_TOKEN }}
          TF_LOG: INFO
        run: |
          tofu apply -auto-approve

      - name: Run OpenTofu Destroy
        working-directory: .github/tofu-tests
        env:
          TF_VAR_organization_name: ${{ secrets.INFRADOTS_ORGANIZATION_NAME }}
          TF_VAR_infradots_token: ${{ secrets.INFRADOTS_TOKEN }}
          TF_LOG: INFO
        if: always()
        run: |
          tofu destroy -auto-approve

